import './styles/globals.scss'

export const metadata = {
  title: 'dashboard',
  description: 'Generated by Moein Parvizi',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
